[package]
name = "send-temp-to-aws-iot-with-rpi"
version = "0.1.0"
authors = ["iam326 <xxx>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.11.3"
